let a = "Thu Feb 10 2022 11:17:21 GMT+0530 (India Standard Time)";
a = a.slice(4, 14);
// creating data
const datas = [
  {
    id: 1,
    user: {
      pic: "SR",
      firstName: "Soafd",
      lastName: "rwerwe",
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 35,
    v: 0,
  },
  {
    id: 2,
    user: {
      pic: "LC",
      lastName: "Lannister",
      firstName: "Cersei",
      email: "abc@gmail.com",
    },
    Booking: "pending",
    roomType: "classic",
    arrive: a,
    payment: "due",
    age: 42,
    v: 0,
  },
  {
    id: 3,
    user: {
      pic: "LC",
      lastName: "Lannister",
      firstName: "Jaime",
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 45,
    v: 0,
  },
  {
    id: 4,
    user: {
      pic: "LC",
      lastName: "Stark",
      firstName: "Arya",
      email: "abc@gmail.com",
    },
    Booking: "pending",
    roomType: "classic",
    arrive: a,
    payment: "due",
    age: 16,
    v: 0,
  },
  {
    id: 5,
    user: {
      pic: "LC",
      lastName: "Targaryen",
      firstName: "Daenerys",
      email: "abc@gmail.com",
    },
    Booking: "active",
    aroomType: "classic",
    arrive: a,
    payment: "paid",
    ge: null,
    v: 0,
  },
  {
    id: 6,
    user: {
      pic: "LC",
      lastName: "Melisandre",
      firstName: null,
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 150,
    v: 0,
  },
  {
    id: 7,
    user: {
      pic: "LC",
      lastName: "Clifford",
      firstName: "Ferrara",
      email: "abc@gmail.com",
    },
    Booking: "pending",
    roomType: "classic",
    arrive: a,
    payment: "due",
    age: 44,
    v: 0,
  },
  {
    id: 8,
    user: {
      pic: "LC",
      lastName: "Frances",
      firstName: "Rossini",
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 36,
    v: 0,
  },
  {
    id: 9,
    user: {
      pic: "LC",
      lastName: "Roxie",
      firstName: "Harvey",
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 65,
    v: 0,
  },
  {
    id: 1,
    user: {
      pic: "SR",
      firstName: "Soafd",
      lastName: "rwerwe",
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 35,
    v: 0,
  },
  {
    id: 2,
    user: {
      pic: "LC",
      lastName: "Lannister",
      firstName: "Cersei",
      email: "abc@gmail.com",
    },
    Booking: "pending",
    roomType: "classic",
    arrive: a,
    payment: "due",
    age: 42,
    v: 0,
  },
  {
    id: 3,
    user: {
      pic: "LC",
      lastName: "Lannister",
      firstName: "Jaime",
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 45,
    v: 0,
  },
  {
    id: 4,
    user: {
      pic: "LC",
      lastName: "Stark",
      firstName: "Arya",
      email: "abc@gmail.com",
    },
    Booking: "pending",
    roomType: "classic",
    arrive: a,
    payment: "due",
    age: 16,
    v: 0,
  },
  {
    id: 5,
    user: {
      pic: "LC",
      lastName: "Targaryen",
      firstName: "Daenerys",
      email: "abc@gmail.com",
    },
    Booking: "active",
    aroomType: "classic",
    arrive: a,
    payment: "paid",
    ge: null,
    v: 0,
  },
  {
    id: 6,
    user: {
      pic: "LC",
      lastName: "Melisandre",
      firstName: null,
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 150,
    v: 0,
  },
  {
    id: 7,
    user: {
      pic: "LC",
      lastName: "Clifford",
      firstName: "Ferrara",
      email: "abc@gmail.com",
    },
    Booking: "pending",
    roomType: "classic",
    arrive: a,
    payment: "due",
    age: 44,
    v: 0,
  },
  {
    id: 8,
    user: {
      pic: "LC",
      lastName: "Frances",
      firstName: "Rossini",
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 36,
    v: 0,
  },
  {
    id: 9,
    user: {
      pic: "LC",
      lastName: "Roxie",
      firstName: "Harvey",
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 65,
    v: 0,
  },
  {
    id: 1,
    user: {
      pic: "SR",
      firstName: "Soafd",
      lastName: "rwerwe",
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 35,
    v: 0,
  },
  {
    id: 2,
    user: {
      pic: "LC",
      lastName: "Lannister",
      firstName: "Cersei",
      email: "abc@gmail.com",
    },
    Booking: "pending",
    roomType: "classic",
    arrive: a,
    payment: "due",
    age: 42,
    v: 0,
  },
  {
    id: 3,
    user: {
      pic: "LC",
      lastName: "Lannister",
      firstName: "Jaime",
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 45,
    v: 0,
  },
  {
    id: 4,
    user: {
      pic: "LC",
      lastName: "Stark",
      firstName: "Arya",
      email: "abc@gmail.com",
    },
    Booking: "pending",
    roomType: "classic",
    arrive: a,
    payment: "due",
    age: 16,
    v: 0,
  },
  {
    id: 5,
    user: {
      pic: "LC",
      lastName: "Targaryen",
      firstName: "Daenerys",
      email: "abc@gmail.com",
    },
    Booking: "active",
    aroomType: "classic",
    arrive: a,
    payment: "paid",
    ge: null,
    v: 0,
  },
  {
    id: 6,
    user: {
      pic: "LC",
      lastName: "Melisandre",
      firstName: null,
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 150,
    v: 0,
  },
  {
    id: 7,
    user: {
      pic: "LC",
      lastName: "Clifford",
      firstName: "Ferrara",
      email: "abc@gmail.com",
    },
    Booking: "pending",
    roomType: "classic",
    arrive: a,
    payment: "due",
    age: 44,
    v: 0,
  },
  {
    id: 8,
    user: {
      pic: "LC",
      lastName: "Frances",
      firstName: "Rossini",
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 36,
    v: 0,
  },
  {
    id: 9,
    user: {
      pic: "LC",
      lastName: "Roxie",
      firstName: "Harvey",
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 65,
    v: 0,
  },
  {
    id: 1,
    user: {
      pic: "SR",
      firstName: "Soafd",
      lastName: "rwerwe",
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 35,
    v: 0,
  },
  {
    id: 2,
    user: {
      pic: "LC",
      lastName: "Lannister",
      firstName: "Cersei",
      email: "abc@gmail.com",
    },
    Booking: "pending",
    roomType: "classic",
    arrive: a,
    payment: "due",
    age: 42,
    v: 0,
  },
  {
    id: 3,
    user: {
      pic: "LC",
      lastName: "Lannister",
      firstName: "Jaime",
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 45,
    v: 0,
  },
  {
    id: 4,
    user: {
      pic: "LC",
      lastName: "Stark",
      firstName: "Arya",
      email: "abc@gmail.com",
    },
    Booking: "pending",
    roomType: "classic",
    arrive: a,
    payment: "due",
    age: 16,
    v: 0,
  },
  {
    id: 5,
    user: {
      pic: "LC",
      lastName: "Targaryen",
      firstName: "Daenerys",
      email: "abc@gmail.com",
    },
    Booking: "active",
    aroomType: "classic",
    arrive: a,
    payment: "paid",
    ge: null,
    v: 0,
  },
  {
    id: 6,
    user: {
      pic: "LC",
      lastName: "Melisandre",
      firstName: null,
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 150,
    v: 0,
  },
  {
    id: 7,
    user: {
      pic: "LC",
      lastName: "Clifford",
      firstName: "Ferrara",
      email: "abc@gmail.com",
    },
    Booking: "pending",
    roomType: "classic",
    arrive: a,
    payment: "due",
    age: 44,
    v: 0,
  },
  {
    id: 8,
    user: {
      pic: "LC",
      lastName: "Frances",
      firstName: "Rossini",
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 36,
    v: 0,
  },
  {
    id: 9,
    user: {
      pic: "LC",
      lastName: "Roxie",
      firstName: "Harvey",
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 65,
    v: 0,
  },
  {
    id: 1,
    user: {
      pic: "SR",
      firstName: "Soafd",
      lastName: "rwerwe",
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 35,
    v: 0,
  },
  {
    id: 2,
    user: {
      pic: "LC",
      lastName: "Lannister",
      firstName: "Cersei",
      email: "abc@gmail.com",
    },
    Booking: "pending",
    roomType: "classic",
    arrive: a,
    payment: "due",
    age: 42,
    v: 0,
  },
  {
    id: 3,
    user: {
      pic: "LC",
      lastName: "Lannister",
      firstName: "Jaime",
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 45,
    v: 0,
  },
  {
    id: 4,
    user: {
      pic: "LC",
      lastName: "Stark",
      firstName: "Arya",
      email: "abc@gmail.com",
    },
    Booking: "pending",
    roomType: "classic",
    arrive: a,
    payment: "due",
    age: 16,
    v: 0,
  },
  {
    id: 5,
    user: {
      pic: "LC",
      lastName: "Targaryen",
      firstName: "Daenerys",
      email: "abc@gmail.com",
    },
    Booking: "active",
    aroomType: "classic",
    arrive: a,
    payment: "paid",
    ge: null,
    v: 0,
  },
  {
    id: 6,
    user: {
      pic: "LC",
      lastName: "Melisandre",
      firstName: null,
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 150,
    v: 0,
  },
  {
    id: 7,
    user: {
      pic: "LC",
      lastName: "Clifford",
      firstName: "Ferrara",
      email: "abc@gmail.com",
    },
    Booking: "pending",
    roomType: "classic",
    arrive: a,
    payment: "due",
    age: 44,
    v: 0,
  },
  {
    id: 8,
    user: {
      pic: "LC",
      lastName: "Frances",
      firstName: "Rossini",
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 36,
    v: 0,
  },
  {
    id: 9,
    user: {
      pic: "LC",
      lastName: "Roxie",
      firstName: "Harvey",
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 65,
    v: 0,
  },
  {
    id: 1,
    user: {
      pic: "SR",
      firstName: "Soafd",
      lastName: "rwerwe",
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 35,
    v: 0,
  },
  {
    id: 2,
    user: {
      pic: "LC",
      lastName: "Lannister",
      firstName: "Cersei",
      email: "abc@gmail.com",
    },
    Booking: "pending",
    roomType: "classic",
    arrive: a,
    payment: "due",
    age: 42,
    v: 0,
  },
  {
    id: 3,
    user: {
      pic: "LC",
      lastName: "Lannister",
      firstName: "Jaime",
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 45,
    v: 0,
  },
  {
    id: 4,
    user: {
      pic: "LC",
      lastName: "Stark",
      firstName: "Arya",
      email: "abc@gmail.com",
    },
    Booking: "pending",
    roomType: "classic",
    arrive: a,
    payment: "due",
    age: 16,
    v: 0,
  },
  {
    id: 5,
    user: {
      pic: "LC",
      lastName: "Targaryen",
      firstName: "Daenerys",
      email: "abc@gmail.com",
    },
    Booking: "active",
    aroomType: "classic",
    arrive: a,
    payment: "paid",
    ge: null,
    v: 0,
  },
  {
    id: 6,
    user: {
      pic: "LC",
      lastName: "Melisandre",
      firstName: null,
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 150,
    v: 0,
  },
  {
    id: 7,
    user: {
      pic: "LC",
      lastName: "Clifford",
      firstName: "Ferrara",
      email: "abc@gmail.com",
    },
    Booking: "pending",
    roomType: "classic",
    arrive: a,
    payment: "due",
    age: 44,
    v: 0,
  },
  {
    id: 8,
    user: {
      pic: "LC",
      lastName: "Frances",
      firstName: "Rossini",
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 36,
    v: 0,
  },
  {
    id: 9,
    user: {
      pic: "LC",
      lastName: "Roxie",
      firstName: "Harvey",
      email: "abc@gmail.com",
    },
    Booking: "active",
    roomType: "classic",
    arrive: a,
    payment: "paid",
    age: 65,
    v: 0,
  },
];

export default datas;