export const FIRST_STEP_OB_REQUEST = "FIRST_STEP_OB_REQUEST";
export const FIRST_STEP_OB_SUCCESS = "FIRST_STEP_OB_SUCCESS";
export const FIRST_STEP_OB_FAIL = "FIRST_STEP_OB_FAIL";

export const STREE_ADDRESS_REQUEST = "STREE_ADDRESS_REQUEST";
export const STREE_ADDRESS_SUCCESS = "STREE_ADDRESS_SUCCESS";
export const STREE_ADDRESS_FAIL = "STREE_ADDRESS_FAIL";

export const OUR_AMENTIES_SAVE_REQUEST = "OUR_AMENTIES_SAVE_REQUEST";
export const OUR_AMENTIES_SAVE_SUCCESS = "OUR_AMENTIES_SAVE_SUCCESS";
export const OUR_AMENTIES_SAVE_FAIL = "OUR_AMENTIES_SAVE_FAIL";

export const ADD_PHOTO_ON_REQUEST = "ADD_PHOTO_ON_REQUEST";
export const ADD_PHOTO_ON_SUCCESS = "ADD_PHOTO_ON_SUCCESS";
export const ADD_PHOTO_ON_FAIL = "ADD_PHOTO_ON_FAIL";

export const CONFIG_ROOM_REQUEST = "CONFIG_ROOM_REQUEST";
export const CONFIG_ROOM_SUCCESS = "CONFIG_ROOM_SUCCESS";
export const CONFIG_ROOM_FAIL = "CONFIG_ROOM_FAIL";

export const CLEAR_ERRORS = "CLEARE_ERRORS";
